version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_GOOGLE_CLIENT_ID: ${REACT_APP_GOOGLE_CLIENT_ID}
        REACT_APP_FACEBOOK_CLIENT_ID: ${REACT_APP_FACEBOOK_CLIENT_ID}
        REACT_APP_BACKEND_API_HOST: ${REACT_APP_BACKEND_API_HOST}
    environment:
      - REACT_APP_BACKEND_API_HOST=${REACT_APP_BACKEND_API_HOST}
      - REACT_APP_GOOGLE_CLIENT_ID=${REACT_APP_GOOGLE_CLIENT_ID}
      - REACT_APP_FACEBOOK_CLIENT_ID=${REACT_APP_FACEBOOK_CLIENT_ID}
    ports:
      - "3000:3000"

  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7777:80"
